### ISSUE TITLE
Instead of flowers for wedding

### ISSUE THREAD

**Issue by brntbeer** [MissG/Test-Tank#3]
Why not have origami designs as well as paper flowers??

also omg congrats!

**Comment by MissG** [comment]
Thanks dude! That's a great idea :)

Side note: thanks for last night's/yesterdays training :)

**Comment by brntbeer** [comment]
You're welcome!

**Comment by brntbeer** [comment]
Going to close this out since this was probably for some training class and for practice anyways!
